### ISSUE TITLE
setwd() successfully eliminated?

### ISSUE THREAD

**Issue by remi-daigle** [OHI-Science/can-atl#1]
Hey @jules32, I noticed that some of the setwd() avoidance strategy was implemented, but not all of it. Is there a reason for that? In any case, this commit https://github.com/OHI-Science/can-atl/commit/41f00649011fb49645b8258ce1466c30e75c3c4c fixes it on my Windows machine (i.e. I can now run the calculate_scores.R without errors), does it still work on Mac?

**Comment by jules32** [comment]
Hi @remi-daigle, yes this still works. I should have double-checked this before passing it over to you. Thanks!
